# https://taskfile.dev

version: "3"

vars:
  PLUGIN_DIR: tools/protoc-gen-nats-micro
  PLUGIN_BIN: "{{.PLUGIN_DIR}}/protoc-gen-nats-micro{{exeExt}}"

tasks:
  default:
    desc: Generate all protobuf code
    cmds:
      - task: generate

  # Phase 1: Generate extension types (natsmicro/options.proto)
  generate:extensions:
    desc: Generate protobuf extensions (phase 1)
    cmds:
      - buf generate --path extensions/proto/natsmicro/options.proto
      # The plugin imports from tools/.../nats/micro, so sync the generated file there too
      - cp gen/nats/micro/options.pb.go tools/protoc-gen-nats-micro/nats/micro/options.pb.go
    sources:
      - extensions/proto/natsmicro/options.proto
      - buf.gen.yaml
    generates:
      - gen/nats/micro/options.pb.go
      - tools/protoc-gen-nats-micro/nats/micro/options.pb.go

  # Phase 2: Build the protoc plugin
  build:plugin:
    desc: Build protoc-gen-nats-micro plugin
    deps:
      - generate:extensions
    cmds:
      - go build -o {{.PLUGIN_BIN}} ./{{.PLUGIN_DIR}}
    sources:
      - "{{.PLUGIN_DIR}}/**/*.go"
      - "{{.PLUGIN_DIR}}/generator/templates/**/*.tmpl"
      - gen/nats/micro/options.pb.go
    generates:
      - "{{.PLUGIN_BIN}}"

  # Phase 3a: Generate Go code
  generate:go:
    desc: Generate Go protobuf code (NATS + protobuf)
    deps:
      - build:plugin
    cmds:
      - buf generate --template examples/buf-configs/buf.gen.yaml examples/protos
    sources:
      - examples/protos/**/*.proto
      - examples/buf-configs/buf.gen.yaml
      - "{{.PLUGIN_BIN}}"
    generates:
      - examples/complex-go/gen/**/*.pb.go
      - examples/complex-go/gen/**/*_nats.pb.go

  # Phase 3b: Generate TypeScript code
  generate:ts:
    desc: Generate TypeScript protobuf code (NATS + protobuf-ts)
    deps:
      - build:plugin
    cmds:
      - buf generate --template examples/buf-configs/buf.gen.ts.yaml examples/protos
    sources:
      - examples/protos/**/*.proto
      - examples/buf-configs/buf.gen.ts.yaml
      - "{{.PLUGIN_BIN}}"
    generates:
      - examples/simple-ts/gen/**/*.pb.ts
      - examples/simple-ts/gen/**/*_nats.pb.ts

  # Phase 3c: Generate Python code
  generate:python:
    desc: Generate Python protobuf code (NATS + protobuf)
    deps:
      - build:plugin
    cmds:
      - buf generate --template examples/buf-configs/buf.gen.py.yaml extensions/proto
      - buf generate --template examples/buf-configs/buf.gen.py.yaml examples/protos
    sources:
      - examples/protos/**/*.proto
      - extensions/proto/**/*.proto
      - examples/buf-configs/buf.gen.py.yaml
      - "{{.PLUGIN_BIN}}"
    generates:
      - examples/simple-py/gen/**/*_pb2.py
      - examples/simple-py/gen/**/*_nats_pb2.py

  # Phase 3: Generate all languages (Go + TypeScript + Python)
  # Uses cmds (sequential) instead of deps (parallel) so one missing tool
  # doesn't cancel the others. Each target is allowed to fail independently.
  generate:
    desc: Generate all protobuf code (Go + TypeScript + Python)
    cmds:
      - task: generate:go
        ignore_error: true
      - task: generate:ts
        ignore_error: true
      - task: generate:python
        ignore_error: true

  # Clean generated files
  clean:
    desc: Remove all generated files
    cmds:
      - rm -rf gen/
      - rm -rf examples/complex-go/gen/
      - rm -rf examples/simple-ts/gen/
      - rm -rf examples/simple-py/gen/
      - rm -f {{.PLUGIN_BIN}}

  # Build Go examples
  build:go:
    desc: Build Go example applications
    deps:
      - generate:go
    cmds:
      - go build -C examples/complex-go -o server ./server.go
      - go build -C examples/complex-go -o client ./client.go

  # Build TypeScript examples
  build:ts:
    desc: Build TypeScript example applications
    deps:
      - generate:ts
    dir: examples/simple-ts
    cmds:
      - npm install
      - npm run build

  # Build all examples
  build:
    desc: Build all example applications (Go + TypeScript)
    deps:
      - build:go
      - build:ts

  # Run tests
  test:
    desc: Run all tests
    deps:
      - generate
    cmds:
      - go test ./...

  # Start NATS server
  nats:
    desc: Start NATS server in Docker
    cmds:
      - docker run --rm -p 4222:4222 --name nats nats

  # Run Go server example
  run:go:server:
    desc: Run Go server example
    deps:
      - generate:go
    cmds:
      - go run examples/complex-go/server.go

  # Run Go client example
  run:go:client:
    desc: Run Go client example
    deps:
      - generate:go
    cmds:
      - go run examples/complex-go/client.go

  # Setup Python venv
  setup:python:
    desc: Setup Python virtual environment and install dependencies
    dir: examples/simple-py
    cmds:
      - python -m venv venv
      - ./venv/bin/pip install -r requirements.txt
    sources:
      - requirements.txt
    generates:
      - venv/
    status:
      - test -d venv

  # Run Python server
  run:python:server:
    desc: Run Python server example
    deps:
      - generate:python
      - setup:python
    dir: examples/simple-py
    cmds:
      - ./venv/bin/python server.py

  # Run Python client
  run:python:client:
    desc: Run Python client example
    deps:
      - generate:python
      - setup:python
    dir: examples/simple-py
    cmds:
      - ./venv/bin/python client.py
