package generator

import (
	"fmt"
	"time"

	"google.golang.org/protobuf/compiler/protogen"
	"google.golang.org/protobuf/proto"

	natspb "github.com/toyz/protoc-gen-nats-micro/gen/nats/micro"
)

// ServiceOptions contains metadata about a service
type ServiceOptions struct {
	SubjectPrefix string
	Name          string
	Version       string
	Description   string
	Metadata      map[string]string
	Timeout       time.Duration
	Skip          bool // Skip generation for this service
}

// GetServiceOptions extracts service options from proto service definition
func GetServiceOptions(service *protogen.Service) ServiceOptions {
	serviceName := service.GoName
	subjectPrefix := ToSnakeCase(serviceName)
	
	// Defaults
	opts := ServiceOptions{
		Name:          serviceName,        // Use actual service name (e.g., "ProductService")
		Version:       "1.0.0",
		Description:   fmt.Sprintf("%s - generated by protoc-gen-nats-micro", serviceName),
		SubjectPrefix: subjectPrefix,      // Default to snake_case (e.g., "product_service")
		Metadata:      make(map[string]string),
		Timeout:       0, // No timeout by default
	}

	// Try to read the nats.micro.service extension
	if service.Desc.Options() != nil && proto.HasExtension(service.Desc.Options(), natspb.E_Service) {
		ext := proto.GetExtension(service.Desc.Options(), natspb.E_Service)
		if svcOpts, ok := ext.(*natspb.ServiceOptions); ok {
			// Check skip first - if true, mark it and return early
			if svcOpts.Skip {
				opts.Skip = true
				return opts
			}
			
			if svcOpts.SubjectPrefix != "" {
				opts.SubjectPrefix = svcOpts.SubjectPrefix
			}
			if svcOpts.Name != "" {
				opts.Name = svcOpts.Name
			}
			if svcOpts.Version != "" {
				opts.Version = svcOpts.Version
			}
			if svcOpts.Description != "" {
				opts.Description = svcOpts.Description
			}
			if len(svcOpts.Metadata) > 0 {
				opts.Metadata = svcOpts.Metadata
			}
			if svcOpts.Timeout != nil {
				opts.Timeout = svcOpts.Timeout.AsDuration()
			}
		}
	}

	return opts
}

// EndpointOptions contains metadata about an endpoint
type EndpointOptions struct {
	Skip     bool                  // Skip generation for this endpoint
	Timeout  time.Duration         // Endpoint-specific timeout (0 = use service default)
	Metadata map[string]string     // Endpoint-specific metadata
}

// GetEndpointOptions extracts endpoint options from proto method definition
func GetEndpointOptions(method *protogen.Method) EndpointOptions {
	opts := EndpointOptions{
		Skip:     false,
		Timeout:  0, // 0 means use service default
		Metadata: make(map[string]string),
	}

	// Try to read the nats.micro.endpoint extension
	if method.Desc.Options() != nil && proto.HasExtension(method.Desc.Options(), natspb.E_Endpoint) {
		ext := proto.GetExtension(method.Desc.Options(), natspb.E_Endpoint)
		if endpointOpts, ok := ext.(*natspb.EndpointOptions); ok {
			opts.Skip = endpointOpts.Skip
			if endpointOpts.Timeout != nil {
				opts.Timeout = endpointOpts.Timeout.AsDuration()
			}
			if len(endpointOpts.Metadata) > 0 {
				opts.Metadata = endpointOpts.Metadata
			}
		}
	}

	return opts
}
